### ISSUE TITLE
Bad mtype for repeatable scripts

### ISSUE THREAD

**Issue by thibaultmeyer** [ebean-orm/ebean-dbmigration#10]
It seems that "mtype" for repeatable scripts is not correct. 

Here, an example of SQL files to migrate:
```
R1__update-sequences.sql
V1__permissions.sql
V2__dns-blaclist.sql
V3__root-account.sql
V4__test-application.sql
```

db_migration table

![image](https://cloud.githubusercontent.com/assets/1005086/22399247/f1b7bd1e-e598-11e6-8820-df01fd7e3ea8.png)

**Comment by rbygrave** [comment]
So I think this isn't a bug. I think the issue here is that the above repeatable script starts with "R1__"  rather than "R__".  So the 1 is the problem here.

Does that sound correct? You did get past this?

**Comment by rbygrave** [comment]
Hmm, ok looking to make a change to support "R1__", "R2__" etc.  Note that these don't really match FlywayDB (which has the form of R__comment) but allowing the R1__foo, R2__bar allows the repeatable scripts to have some relative ordering which could be useful.  

Looking to push a fix.
