### ISSUE TITLE
Generated migration sql should quote keywords

### ISSUE THREAD

**Issue by gdoenlen** [ebean-orm/ebean-dbmigration#106]
When you have SQL keywords as your column or table name the generated sql will be incorrect.  In the below sql user and key (on h2) should be quoted so they're not seen as keywords.  The work around is using `@Column` and `@Table`.

```java
@Entity
public class User  {
      @Id
      @GeneratedValue(strategy = GenerationType.IDENTITY)
       private Long id;
       private String key;
}
```
Incorrect:
```sql
create table user (
  id                            bigint generated by default as identity not null,
  key                          varchar(255) not null,
```
Correct:
```sql
create table "user" (
  id                            bigint generated by default as identity not null,
  "key"                        varchar(255) not null,
```

**Comment by rbygrave** [comment]
The expectation is that the model explicitly reflects what want in terms of quoted identifiers (using backticks).  That is using :
```java
@Table(name="`user`")
@Column(name="`key`") 
```
Some people (sql server orientation) go for everything is quoted style - `DatabaseConfig.setAllQuotedIdentifiers(true)`.

Some people (more Postgres/Oracle orientation) would look to avoid quoted identifiers and look to change those columns and tables where possible to avoid quoted identifiers (impact on tooling etc aiming for nothing to need quoted identifiers).

For this case, the expectation is for the model to reflect the use of quoted identifiers via backticks in the table and column name.

**Comment by gdoenlen** [comment]
I figured that was the answer, but figured I'd report it anyway. Thanks Rob.

**Comment by rbygrave** [comment]
Ok cool.  May as well close this issue then.
Cheers, Rob.
