### ISSUE TITLE
ENH: Add methods to check if migration is needed

### ISSUE THREAD

**Issue by thibaultmeyer** [ebean-orm/ebean-dbmigration#11]
I'm working on a Play Framework module to implement Ebean migration. It could be nice to have methods to check if migration is needed and which migrations files have to be processed.

```
Boolean isMigrationNeeded()  // Check without returning any informations, just true or false
List<LocalMigrationResource> checkState()  // Check and give information on which files will be processed
```

The purpose is to only enable DB migration when it was needed and to show a migration screen when Play is on "DEVEL" mode:

![image](https://cloud.githubusercontent.com/assets/1005086/22403499/23158ac8-e619-11e6-8ea8-be401e5bf617.png)

**Comment by rbygrave** [comment]
Adding the checkState() method like:

```java
    MigrationRunner runner = new MigrationRunner(config);

    // returns the migrations that would be applied if the migration is run.
    List<LocalMigrationResource> pendingMigrations = runner.checkState();
```
