### ISSUE TITLE
ENH: Add "dev" mode such that modified scripts are run (when otherwise the checksum has changed and they do not run)

### ISSUE THREAD

**Issue by thibaultmeyer** [ebean-orm/ebean-dbmigration#12]
Hi,

I got an issue with the migration. I have 5 scripts:

```
R__update-sequences.sql
V1__permissions.sql
V2__dns-blaclist.sql
V3__root-account.sql
V4__test-application.sql
```

First time, all scripts has been processed with success. But I have edited the last script (V4__test-application.sql), and no migration has been done. The file is not processed.

I understand the choice to not allow edited scripts to be processed if are already processed in past. Maybe a boolean option to allow the migration of a script already migrated if it was edited. To enable this on "dev" mode and not in "production".

**Comment by rbygrave** [comment]
The fix for this is to add to `MigrationConfig`  `skipChecksum`.

When this is set to true then the checksum checking is skipped.
