### ISSUE TITLE
Entry duplication on db_migration table

### ISSUE THREAD

**Issue by thibaultmeyer** [ebean-orm/ebean-dbmigration#13]
Repeatable, when executed, create a new entry on db_migration table rather than update existing entry.

![image](https://cloud.githubusercontent.com/assets/1005086/22428327/f232b00e-e706-11e6-843f-e2d5101e4518.png)

**Comment by rbygrave** [comment]
Originally I was happy to keep the "log" of when the repeatable migrations ran ... but in review I think it is better to be a bit more 'minimal' and treat this as a bug and not have the duplicate entries.

Fix in the commit just pushed.
