### ISSUE TITLE
[Question] How to add custom SQL

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [ebean-orm/ebean-dbmigration#135]
Hi @rbygrave,

We would like to use ebean-migration and be able to run custom SQL for specific migration version.
For example, creating SQL function or complex constraints.

We are currently using db migration generation through : 
```
DbMigration dbMigration = DbMigration.create();
dbMigration.setPlatform(Platform.POSTGRES);
dbMigration.generateMigration();
```

We were wondering if there was a special Java annotation to add cusotm SQL.
Or maybe we have to create the XML schema change descriptor by hand ?
If yes, do you have an example of good format for pure SQL apply ?

Thanks in advance for your help.
Yours faithfully,
LCDP

**Comment by rbygrave** [comment]
2 options. 

**Option 1**: Add a extra-ddl.xml file with the extra ddl that we want to include (like https://github.com/ebean-orm/ebean/blob/master/ebean-test/src/test/resources/extra-ddl.xml).  

We use this option when we want ebean to also run the extra ddl during testing after the `create-all.sql`


**Option 2**: Just add a sql migration manually with the version we want. It does not need a corresponding model xml file. This is just a manually added migration that will be executed when running migrations.

If using ebean-test and we want that ddl executed for testing then potentially change the ddlMode from `dropCreate` to `migration`.

**Comment by rPraml** [comment]
*Option 3*: Take a look at `@DbMigration` annotation. Depending on your use case (adding fields/changing data type) this might be the right choice.

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Thanks a lot for your answers @rbygrave and @rPraml !

Option 1 : 
That sounds good, we tried to put the `extra-ddl.xml` file next to our generated model XML files but : 
- The `generateMigration` do not generate SQL contained into the XML
- On start, the contained SQL is not executed against the database

Example of extra-ddl : 
![image](https://github.com/ebean-orm/ebean-migration/assets/104082030/225894ba-95b8-4678-9498-ddc7aadb5a0a)

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<extra-ddl xmlns="http://ebean-orm.github.io/xml/ns/extraddl">

    <ddl-script name="Add product insight constraint" platforms="postgres" drop="true">
        ALTER TABLE product_insight ADD CONSTRAINT ck_principal
            CHECK (principal IS NOT DISTINCT FROM cip OR principal IS NOT DISTINCT FROM cip13 OR principal = ANY(eans));
    </ddl-script>
</extra-ddl>
```

Options 2 :
This is the only solution that worked at the moment. It is a good news to know that the XML model file is not necessary in this context. 👍 

Option 3 : 
For the moment, I tried to use `@DbMigration` in order to add a complex constraint, without success.
Maybe we are missing something here ?
```
    [...]
    @Column(nullable = false)
    @DbMigration(
            platforms = {Platform.POSTGRES},
            postAdd = "ALTER TABLE product_insight ADD CONSTRAINT ck_principal\n" +
                    "    CHECK (principal IS NOT DISTINCT FROM cip OR principal IS NOT DISTINCT FROM cip13 OR principal = ANY(eans));\n"
    )
    private String principal;
    [...]
```

Yours faithfully,
LCDP

**Comment by rbygrave** [comment]
> we tried to put the extra-ddl.xml file next to our generated model XML files

It needs to be at the top level like `resources/extra-ddl.xml`

**Comment by rPraml** [comment]
> Option 3 :
> For the moment, I tried to use `@DbMigration` in order to add a complex constraint, without success.
> Maybe we are missing something here ?


Hello,
`@DbMigration` will not work for initial scripts, but only for delta scripts. (there is no "postInit")
Maybe it's not for your use case

Short example:
```java
class MyBean {
   @Id;
   int id;

  String foo;
}
```

Generate migration now -> you'll get a `create table my_bean(id integer, foo varchar(255))` as 1.0__initial

Add properties to class. E.g.
```java
class MyBean {
   @Id;
   int id;

  String foo;

  @DbMigration(postAdd = "ALTER TABLE ${table} ADD CONSTRAINT ck_principal ..." )
  private String principal;
}
```
now you should get a 1.1 migration script with
```sql
alter table my_bean add column principal varchar(255);
ALTER TABLE my_bean ADD CONSTRAINT ck_principal ...
```

**Comment by rbygrave** [comment]
I think we can close this right?  I'll close, re-open if required.
