### ISSUE TITLE
Problems with LogicalLock.

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean-dbmigration#137]
Hello Rob,

with #107 we introduced a "LogicalLock". This means that dbmigration maintains the lock state in the 0-id entry in the lock table.

As long as everything works without errors, the logical lock works fine.

We noted some issues or have the wrong expections:

**Problems**

1. If the server goes away (or the client will be killed), the lock stays always on `locked` and will never get reverted to `<init>`
2. If one of the migration scripts fails partially, the [unlockMigrationTable](https://github.com/ebean-orm/ebean-migration/blob/e998a87268b3a9a849e92e4b1f34b524c8c180e0/ebean-migration/src/main/java/io/ebean/migration/runner/MigrationPlatform.java#L123) performs a commit, which commits the partial work of this script
3. DB2 performs a commit on `reorg table` and mariadb also performs an autocommit on data model changes.

Now, if really something in the migration fails, this costs a lot of effort, to get the app back running.
You should know, that we run our application in financial insititutes, where the DBAs cannot easily access the DB and manipulate some table data - and - as we run the app in a multi tenant setup, where each tenant has its own set of tables, the failure often occurs in more than one tenant. So we need some kind of automation here.

Currently, we have to buld a new application release with new migration scripts (often targeted only to this customer)

**Expectations**

*Commit after each script*
If a script is executed successfully, this should be committed to the DB. I've added a change in #56 - but this was reverted, as it affects locking. Especially, if the DB does an implicit auto commit (and do not use LogicalLock), you may end up with lots executed migration scripts, but not listed in migration table.

*Easier fix of failed migrations*
If scripts fail partially, this is really the worst thing that can happen and if the DB isn't strictly transactional (like mariadb or db2 after a reorg), It would be great, if there is a mechanism, how to control the next DB migration run.
A lot of is already possible with `patchInsertOn` and so on, but I cannot modify existing files without building a new application.
It would be great, if I can ship some patch file (e.g. patch.yml, which is auto detected and may add or override existing migrations)

```yaml
dbmigration:
  files:
    V2_123__blah.sql:
       # this overrides the original V2_123__blah.sql
       - update mytable set fix = 1;
       - update othertable set fix = 1;
  patchinserton:  1.111
```

*Locks never released*
The logical lock may be never released (this is bad for the app-server guy, which has no DB access, as he can not continue with installation.)
We additionally use [Hazelcast-IMap](https://docs.hazelcast.org/docs/4.0/javadoc/com/hazelcast/map/IMap.html#tryLock-K-) in our application, so in our case we can be sure, that only one cluster partner will run the migration code, so in this case, we would not need a lock at all...

@rbygrave maybe you can give some feedback, if I go into the right direction here.

**Comment by rbygrave** [comment]
> If one of the migration scripts fails partially, the [unlockMigrationTable](https://github.com/ebean-orm/ebean-migration/blob/e998a87268b3a9a849e92e4b1f34b524c8c180e0/ebean-migration/src/main/java/io/ebean/migration/runner/MigrationPlatform.java#L123) performs a commit, which commits the partial work of this script

Looks like we need a failing test case for this.

It looks like either the LogicalLock unlock should do an additional rollback() before it unlocks() or we look to add some catch blocks in before the finally does the unlock.

**Comment by rbygrave** [comment]
There might be some outstanding questions here but the PR fixes the noted issue with LogicalLock and unlock()

**Comment by rPraml** [comment]
Yes, the issue 2 is solved (failed migration will be partially committed by unlock)
