### ISSUE TITLE
Migrations generating Postgres Array as "array"

### ISSUE THREAD

**Issue by IvanAR** [ebean-orm/ebean-dbmigration#14]
Hi, when running database migration on Postgres platform in a array type as below
```java
@DbArray
private List<String> parameterValue;
```  
Ebean is generating it's type as "array" instead of "varchar(255)[]" causing errors on migration run.
```sql
create table parameter (
  id                            uuid not null,
  parameter_key                 varchar(255),
  parameter_value               array,
  required                      boolean,
  version                       bigint not null,
  create_date                   timestamptz not null,
  update_date                   timestamptz not null,
  constraint pk_parameter primary key (id)
);
```
Using `io.ebean:ebean-dbmigration:10.1.3`

**Comment by thibaultmeyer** [comment]
Db migration dont generate DDL. Maybe you speak about [ebean-orm/ebean](https://github.com/ebean-orm/ebean) ?


We are using @DbArray with [ebean-orm/ebean](https://github.com/ebean-orm/ebean) 10.1.5. The generated DDL is correct (VARCHAR[])

**Comment by IvanAR** [comment]
Hi, I'm trying to generate DDL using `dbMigration.generateMigration();` and even with ebean 10.1.5 and ebean-dbmigration 10.1.2 it still generates with `array`

**Comment by rbygrave** [comment]
The https://github.com/ebean-orm-examples/example-java8 ... has an @DbArray type on Customer.  It would be good to confirm that you can:
- clone that repo 
- remove the migration model and sql from src/main/resources/dbmigration
- run src/test/java/main/MainDbMigration
- ... observe if the issue reproduces there

Might be worth doing a `mvn dependency:tree` and confirm there are no older versions of Ebean in the classpath.

**Comment by rbygrave** [comment]
I think we can close this now right?  The issue being we needed to run 'offline' with programmatic ServerConfig ... https://github.com/ebean-orm/ebean/issues/966

**Comment by rbygrave** [comment]
I'm sure we can close this (so doing do). Please reopen if required.
