### ISSUE TITLE
SQL syntax error with SQLite

### ISSUE THREAD

**Issue by Mijyuoon** [ebean-orm/ebean-dbmigration#25]
Migration runner fails with SQL syntax error when SQLite is used as target DB platform.

The problem is because of [this code](https://github.com/ebean-orm/ebean-dbmigration/blob/master/src/main/java/io/ebean/dbmigration/runner/MigrationMetaRow.java#L110-L112). It uses `SELECT _ FOR UPDATE` statement that SQLite does not support. 

I believe simply replacing it with normal `SELECT` when SQLite is used should work without causing any problems.

**Comment by rbygrave** [comment]
Fixed.  So with SQLite we won't have locking on the migration table.
