### ISSUE TITLE
Option to disable "FOR UPDATE"

### ISSUE THREAD

**Issue by thibaultmeyer** [ebean-orm/ebean-dbmigration#37]
It could be nice to add option to disable usage of `FOR UPDATE` on the queries like

```
select id, mtype, mstatus, mversion, mcomment, mchecksum, run_on, run_by, run_time from db_migration order by id for update
```

It will allow usage of database like CockroachDB who is using PostgreSQL driver but don't have all sub-feature like `FOR UPDATE`.

**Comment by rbygrave** [comment]
Pretty sure you can ... by specifying a resource to override the 'platform selected' resource (that has the sql in it).

It is also 'platform aware' ... so could make it CockroachDB aware.

**Comment by rbygrave** [comment]
Closing this as we have merged in https://github.com/ebean-orm/ebean-migration/pull/38

Great work, thanks.
