### ISSUE TITLE
ENH: Add support for DdlRunner.setCommitOnCreateIndex() ... for CockroachDB support

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-dbmigration#39]
Without this turned on .. then alter table add foreign key fails even when the create index is run before it. 

So this DDL ...
```sql
create index ix_address_country_code on address (country_code);

alter table address add constraint fk_address_country_code foreign key (country_code) references country (code) on delete restrict on update restrict;
```
... fails running with the following error.

```
Error executing stmt[alter table address add constraint fk_address_country_code foreign key (country_code) references country (code) on delete restrict on update restrict] error[ERROR: foreign key requires an existing index on columns ("country_code")]
```

This option puts a commit after each `create index ...` which seems less than ideal but at least we have all the table creation succeeding or failing together before that.

**Comment by thibaultmeyer** [comment]
Next major version of cockroach (2.x) will be released at the end of March 2018. This new version be more compatible with PostgreSQL behaviour like any(), json_*(), ...

You can use preview build: https://www.cockroachlabs.com/docs/dev/install-cockroachdb.html
