### ISSUE TITLE
Migration is not working properly!

### ISSUE THREAD

**Issue by batzorigt** [ebean-orm/ebean-dbmigration#76]
Migration on startup is working only for following settings:
ebean.migration.run = true
ebean.ddl.generate = true
ebean.ddl.run = true

But, it always drops and creates the db.
I want to update my db with migration.

**Comment by batzorigt** [comment]
offline db migration does not create properly sql files for following case:
- create table: OK. It is generated sql file.
- add column: OK. It is generated sql file.
- remove column that is added by previous migration: NG. Not generated sql file!
   ```
    DbMigration dbMigration = DbMigration.create();
    dbMigration.setPlatform(Platform.POSTGRES);

    // generate the migration ddl and xml
    dbMigration.generateMigration();
```
xml is generated correctly. But, I do not know to use these xml files.
These xml files are liquibase formatted files?
Generated sql files are intended for flywayDB?

**Comment by rbygrave** [comment]
> Migration on startup is working only for following settings:
> ebean.migration.run = true
> ebean.ddl.generate = true
> ebean.ddl.run = true

> But, it always drops and creates the db. I want to update my db with migration.

Do not include `ebean.ddl.generate` or `ebean.ddl.run` for running db migrations.  We only need `ebean.migration.run = true`.
Refer to https://ebean.io/docs/db-migrations/

Refer to https://ebean.io/docs/ddl-generation/ ... wrt `ebean.ddl.generate` and `ebean.ddl.run`


> remove column that is added by previous migration: NG. Not generated sql file!

A drop column diff becomes a "pending drop".  A pending drop can not be included immediately in a migration as then the migration would effectively need an outage. That is, pending drops need to be included in a subsequent migration.

Refer to https://ebean.io/docs/db-migrations/detail

**Comment by batzorigt** [comment]
@rbygrave
I have already tried. But, migration only with ebean.migration.run is not working! 
My application.properties file is below. Here, mydb and myschema is created manually.
```
datasource.default = mydb
datasource.otolier.username = username
datasource.otolier.password = password
datasource.otolier.url = jdbc:postgresql://localhost:5432/mydb
datasource.otolier.driver = org.postgresql.Driver

ebean.dbSchema = myschema
ebean.migration.run = true
```

"pending drop" works properly only for xml. It does not work properly for sql file.

**Comment by batzorigt** [comment]
@rbygrave
I have already tried. But, migration only with ebean.migration.run is not working! 
My application.properties file is below. Here, mydb and myschema is created manually.
```
datasource.default = mydb
datasource.otolier.username = username
datasource.otolier.password = password
datasource.otolier.url = jdbc:postgresql://localhost:5432/mydb
datasource.otolier.driver = org.postgresql.Driver

ebean.dbSchema = myschema
ebean.migration.run = true
```

"pending drop" works properly only for xml. It does not work properly for sql file.

**Comment by rbygrave** [comment]
Put a break point into DatabaseConfig line 3041.  This is where Ebean
checks for the migration run to be set to true and then runs the migration.

Put a break point there, run the application, have a look as to why that
does not run ?

**Comment by batzorigt** [comment]
Thank you!

I should have done offline migration first.
It was confusing. I misunderstood that "Generate offline" and "Running migration" is not related.
- Generate offline: We can generate a migration programmatically without starting the application.
- Running migration : With ebean.migration.run=true then when the EbeanServer starts it will look at the migrations and run any that need to be run.

Please update document as following: https://ebean.io/docs/db-migrations/detail
Run migration:
1. Run offline migration to generate DDL scripts.
2. Run your (ebean server)  app. EbeanServer starts it will look at the migrations and run any that need to be run.

**Comment by rbygrave** [comment]
> I should have done offline migration first.

Does this mean there was not a generated migration?  Needed to generate the
migration first?

Thanks, Rob.

**Comment by batzorigt** [comment]
> Does this mean there was not a generated migration? Needed to generate the migration first?

No, no. Migration (ddl scripts) is generated. Root cause was: I ran migration without generation (ddl).
