### ISSUE TITLE
JDBC Connection is left open when no migration was run

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean-dbmigration#96]
Hello @rbygrave, when ebean shuts down, datasource logs
```
Dumping [1] busy connections: (Use datasource.xxx.capturestacktrace=true  ... to get stackTraces)
```

The probem is located at https://github.com/ebean-orm/ebean-migration/blob/master/ebean-migration/src/main/java/io/ebean/migration/MigrationRunner.java#L95

```java
  protected void run(Connection connection, boolean checkStateMode) {
    LocalMigrationResources resources = new LocalMigrationResources(migrationConfig);
    if (!resources.readResources()) {
      log.debug("no migrations to check");
      return;
    }
    try {
      ...
    } finally {
      close(connection);
    }
```

When `resources.readResources()` is empty, the method returns, and `close(connection)` will not be called.

cheers
Roland

**Comment by rbygrave** [comment]
Oh wow !!  Nice catch.
